### ISSUE TITLE
database mistake

### ISSUE THREAD

**Issue by Salvador-ON** [dannisonarias/Users_and_Private_Events_Rails#2]
I found the mistake, you need to change in your migration file 

>  20200415152944_event 

 the creator_id

```
class Event < ActiveRecord::Migration[5.2]
  def change
    create_table :events do |t|
      t.integer :creator_id
      t.string :name
      t.string :date
      t.string :description
      t.timestamps
    end
  end
end
```

**Comment by Salvador-ON** [comment]
and your events model ned to be like

```
class Event < ApplicationRecord
# has_many :attendees,through: :Registrations ,source: User
belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
end

```

and the user model like

```
class User < ApplicationRecord
  # has_many :activities, through: :Registrations ,source: Event
  has_many :events, foreign_key: 'creator_id'
end
```

**Comment by Salvador-ON** [comment]
![image](https://user-images.githubusercontent.com/58054122/79473129-14b20d80-7fdb-11ea-8219-0da07d3df82d.png)

**Comment by Salvador-ON** [comment]
you need to rollback all your migrations and modify the migration that is wrong and migrate again all the migrations

**Comment by dannisonarias** [comment]
I've rollbacked the migration and used your suggested events migration and it fixed the issue! thank you!
